swagger: "2.0"
info:
  version: "0.0.1"
  title: Locations App
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /locations:
    # binds a127 app logic to a route
    x-swagger-router-controller: locations
    post:
      description: Returns the distance between two points
      # used as the method name of the controller
      operationId: getDistance
      parameters:
        - name: points
          in: body
          description: From point
          required: true
          schema:
            $ref: '#/definitions/ModelLine'
      responses:
        "201":
          description: Created
          schema:
            # a pointer to a definition
            $ref: "#/definitions/BaseResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
    get:
      operationId: getHistory
      description: Get previous requests
      responses:
        200:
          description: Ok
          schema:
            type: array
            items:
              $ref: '#/definitions/ModelHistory'
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  BaseResponse:
    properties:
      message:
        type: string
  ModelHistory:
    properties:
      from:
        $ref: '#/definitions/ModelLocation'
      to:
        $ref: '#/definitions/ModelLocation'
      stamp:
        type: string
      distance:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  ModelLine:
    type: object
    required:
      - from
      - to
    properties:
      from:
        $ref: '#/definitions/ModelLocation'
      to:
        $ref: '#/definitions/ModelLocation'
  ModelLocation:
    type: object
    required:
      - lat
      - lon
    properties:
      lat:
        type: number
      lon:
        type: number
        